-- Run this in Supabase SQL Editor to populate cache with facts
-- Go to: https://supabase.com/dashboard/project/libcgvamzfkuhfexxfgz/sql/new

INSERT INTO cached_facts (id, topic, content, source_name, source_url) VALUES
('f1', 'Space', 'A day on Venus is longer than its year - 243 Earth days to rotate once.', 'NASA', 'https://nasa.gov'),
('f2', 'Biology', 'Octopuses have three hearts and blue blood.', 'National Geographic', 'https://nationalgeographic.com'),
('f3', 'History', 'Cleopatra lived closer to the Moon landing than to the Great Pyramid construction.', 'Smithsonian', 'https://smithsonianmag.com'),
('f4', 'Technology', 'The first computer bug was a real moth found in Harvard Mark II in 1947.', 'Computer History', 'https://computerhistory.org'),
('f5', 'Nature', 'Honey never spoils. 3000-year-old honey from Egyptian tombs was still edible.', 'Smithsonian', 'https://smithsonianmag.com'),
('f6', 'Psychology', 'Your brain uses 20% of your energy but is only 2% of your body weight.', 'Scientific American', 'https://scientificamerican.com'),
('f7', 'Ocean', 'We have better maps of Mars than our ocean floor. 80% remains unexplored.', 'NOAA', 'https://noaa.gov'),
('f8', 'Animals', 'Crows recognize human faces and hold grudges for years.', 'Cornell Lab', 'https://birds.cornell.edu'),
('f9', 'Physics', 'If you could fold paper 42 times, it would reach the Moon.', 'Physics Today', 'https://physicstoday.org'),
('f10', 'Human Body', 'Your body has enough iron to make a 3-inch nail.', 'Live Science', 'https://livescience.com'),
('f11', 'Geography', 'Russia has 11 time zones, more than any other country.', 'World Atlas', 'https://worldatlas.com'),
('f12', 'Music', 'The song Happy Birthday was copyrighted until 2016.', 'NPR', 'https://npr.org'),
('f13', 'Food', 'Bananas are berries, but strawberries are not.', 'Britannica', 'https://britannica.com'),
('f14', 'Language', 'The dot over the letters i and j is called a tittle.', 'Merriam-Webster', 'https://merriam-webster.com'),
('f15', 'Sports', 'Golf balls have 336 dimples on average for better aerodynamics.', 'Golf Digest', 'https://golfdigest.com'),
('f16', 'Science', 'Hot water freezes faster than cold water - the Mpemba effect.', 'Nature', 'https://nature.com'),
('f17', 'Art', 'The Mona Lisa has no eyebrows - it was fashion in Renaissance Florence.', 'Louvre', 'https://louvre.fr'),
('f18', 'Medicine', 'Humans share 60% of their DNA with bananas.', 'NIH', 'https://nih.gov'),
('f19', 'Weather', 'Lightning strikes Earth about 8 million times per day.', 'NOAA', 'https://noaa.gov'),
('f20', 'Economics', 'More money is printed for Monopoly than real US currency each year.', 'Hasbro', 'https://hasbro.com'),
('f21', 'Astronomy', 'Neutron stars are so dense a teaspoon would weigh 6 billion tons.', 'NASA', 'https://nasa.gov'),
('f22', 'Chemistry', 'Water can boil and freeze at the same time at the triple point.', 'ACS', 'https://acs.org'),
('f23', 'Architecture', 'The Great Wall of China is not visible from space with naked eye.', 'NASA', 'https://nasa.gov'),
('f24', 'Insects', 'A flea can jump 150 times its body length.', 'Entomology Today', 'https://entomologytoday.org'),
('f25', 'Mathematics', 'More possible chess games exist than atoms in the observable universe.', 'Chess.com', 'https://chess.com'),
('f26', 'Plants', 'Bamboo can grow up to 35 inches in a single day.', 'Botanical Garden', 'https://botanicalgarden.org'),
('f27', 'Movies', 'The Wilhelm scream has been used in over 400 films since 1951.', 'IMDb', 'https://imdb.com'),
('f28', 'Geology', 'Diamonds can be made from peanut butter under extreme pressure.', 'Geology.com', 'https://geology.com'),
('f29', 'Sleep', 'Humans spend about 26 years of their lives sleeping.', 'Sleep Foundation', 'https://sleepfoundation.org'),
('f30', 'Internet', 'The first website ever created is still online at info.cern.ch.', 'CERN', 'https://cern.ch'),
('f31', 'Space', 'There are more stars in the universe than grains of sand on Earth.', 'NASA', 'https://nasa.gov'),
('f32', 'Biology', 'Your nose can detect over 1 trillion different scents.', 'Science Daily', 'https://sciencedaily.com'),
('f33', 'History', 'Oxford University is older than the Aztec Empire.', 'Oxford', 'https://ox.ac.uk'),
('f34', 'Technology', 'The average smartphone has more computing power than NASA in 1969.', 'MIT', 'https://mit.edu'),
('f35', 'Nature', 'A single tree can absorb 48 pounds of CO2 per year.', 'EPA', 'https://epa.gov'),
('f36', 'Psychology', 'It takes 66 days on average to form a new habit.', 'UCL', 'https://ucl.ac.uk'),
('f37', 'Ocean', 'The ocean produces over 50% of the worlds oxygen.', 'NOAA', 'https://noaa.gov'),
('f38', 'Animals', 'Elephants are the only animals that cannot jump.', 'Smithsonian', 'https://smithsonianmag.com'),
('f39', 'Physics', 'Time moves faster at your head than at your feet due to gravity.', 'NIST', 'https://nist.gov'),
('f40', 'Human Body', 'Your heart beats about 100,000 times per day.', 'AHA', 'https://heart.org')
ON CONFLICT (id) DO NOTHING;
